/**
 * OpenAPI schema types. Generated by `npm run generate:api` when the API is running.
 * Placeholder until codegen is run (see README).
 */
export interface paths {}

export type webhooks = Record<string, never>
