/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/payment-methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Payment Methods
         * @description List active payment methods (for dropdowns).
         */
        get: operations["get_payment_methods_api_v1_payment_methods_get"];
        put?: never;
        /**
         * Post Payment Method
         * @description Create a payment method.
         */
        post: operations["post_payment_method_api_v1_payment_methods_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payment-methods/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Payment Method By Id
         * @description Get a single payment method by id (active or inactive).
         */
        get: operations["get_payment_method_by_id_api_v1_payment_methods__id__get"];
        /**
         * Put Payment Method
         * @description Update a payment method by id.
         */
        put: operations["put_payment_method_api_v1_payment_methods__id__put"];
        post?: never;
        /**
         * Delete Payment Method
         * @description Soft delete a payment method by id (set active=False).
         */
        delete: operations["delete_payment_method_api_v1_payment_methods__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Categories
         * @description List active categories (for dropdowns).
         */
        get: operations["get_categories_api_v1_categories_get"];
        put?: never;
        /**
         * Post Category
         * @description Create a category.
         */
        post: operations["post_category_api_v1_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Category By Id
         * @description Get a single category by id (active or inactive).
         */
        get: operations["get_category_by_id_api_v1_categories__id__get"];
        /**
         * Put Category
         * @description Update a category by id.
         */
        put: operations["put_category_api_v1_categories__id__put"];
        post?: never;
        /**
         * Delete Category
         * @description Soft delete a category by id (set active=False).
         */
        delete: operations["delete_category_api_v1_categories__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tag-suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tag Suggestions
         * @description Return up to 20 tag suggestions, optionally filtered by q. Ordered by last_used_at desc.
         */
        get: operations["list_tag_suggestions_api_v1_tag_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ledger-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ledger Entries
         * @description List ledger entries, cursor-paginated, sorted by date desc. Excludes soft-deleted.
         *     Invalid cursor returns first page.
         */
        get: operations["get_ledger_entries_api_v1_ledger_entries_get"];
        put?: never;
        /**
         * Post Ledger Entry
         * @description Create a ledger entry. Category and payment method must exist and be active.
         */
        post: operations["post_ledger_entry_api_v1_ledger_entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ledger-entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ledger Entry By Id
         * @description Get a single ledger entry by id. Returns 404 if not found or soft-deleted.
         */
        get: operations["get_ledger_entry_by_id_api_v1_ledger_entries__id__get"];
        /**
         * Put Ledger Entry
         * @description Update a ledger entry. Same body as POST. Returns 404 if not found or soft-deleted.
         */
        put: operations["put_ledger_entry_api_v1_ledger_entries__id__put"];
        post?: never;
        /**
         * Delete Ledger Entry
         * @description Soft delete a ledger entry (set deleted_at). Idempotent: already-deleted returns 200.
         */
        delete: operations["delete_ledger_entry_api_v1_ledger_entries__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/monthly-expense": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Monthly Expense Route
         * @description Monthly expense and refund aggregates. Only non-deleted entries.
         *     totalExpense = sum(positive amounts), totalRefund = abs(sum(negative amounts)).
         */
        get: operations["get_monthly_expense_route_api_v1_analytics_monthly_expense_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/expense-by-category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Expense By Category Route
         * @description Expense by category for the given month. Positive amounts only; excludes soft-deleted.
         */
        get: operations["get_expense_by_category_route_api_v1_analytics_expense_by_category_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/expense-by-payment-method": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Expense By Payment Method Route
         * @description Expense by payment method for the given month. Positive amounts only; excludes soft-deleted.
         */
        get: operations["get_expense_by_payment_method_route_api_v1_analytics_expense_by_payment_method_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/custom-by-tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Custom Expense By Tags Route
         * @description Total expense (sum of positive amounts) for entries that have all given tags in range.
         *     Excludes soft-deleted entries.
         */
        get: operations["get_custom_expense_by_tags_route_api_v1_analytics_custom_by_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard Route
         * @description Composite dashboard: totalExpense, totalRefund, entryCount, lastEntries (last 5 by date desc).
         *     Excludes soft-deleted entries.
         */
        get: operations["get_dashboard_route_api_v1_analytics_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CategoryCreate
         * @description Request body for creating a category.
         */
        CategoryCreate: {
            /** Name */
            name: string;
            /** Color */
            color?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LedgerEntryCreate
         * @description Request body for creating a ledger entry.
         */
        LedgerEntryCreate: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Description */
            description: string;
            /**
             * Categoryid
             * Format: uuid
             */
            categoryId: string;
            /**
             * Paymentmethodid
             * Format: uuid
             */
            paymentMethodId: string;
            /** Amount */
            amount: number | string;
            /** Tags */
            tags?: string[] | null;
        };
        /**
         * PaymentMethodCreate
         * @description Request body for creating a payment method.
         */
        PaymentMethodCreate: {
            /** Name */
            name: string;
            /** Currency */
            currency: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_payment_methods_api_v1_payment_methods_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of active payment methods */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    post_payment_method_api_v1_payment_methods_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentMethodCreate"];
            };
        };
        responses: {
            /** @description Payment method created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_payment_method_by_id_api_v1_payment_methods__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment method found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Payment method not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid UUID format */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    put_payment_method_api_v1_payment_methods__id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentMethodCreate"];
            };
        };
        responses: {
            /** @description Payment method updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Payment method not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_payment_method_api_v1_payment_methods__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment method soft-deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Payment method not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid UUID format */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_categories_api_v1_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of active categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    post_category_api_v1_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Category created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_category_by_id_api_v1_categories__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Category not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid UUID format */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    put_category_api_v1_categories__id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Category updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Category not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_category_api_v1_categories__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category soft-deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Category not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid UUID format */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_tag_suggestions_api_v1_tag_suggestions_get: {
        parameters: {
            query?: {
                /** @description Optional filter (case-insensitive substring) */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tag suggestions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ledger_entries_api_v1_ledger_entries_get: {
        parameters: {
            query?: {
                /** @description Opaque cursor for next page */
                cursor?: string | null;
                /** @description Page size */
                limit?: number;
                /** @description Filter from date (inclusive) */
                dateFrom?: string | null;
                /** @description Filter to date (inclusive) */
                dateTo?: string | null;
                categoryId?: string | null;
                paymentMethodId?: string | null;
                /** @description expense=amount<0, refund=amount>0 */
                type?: ("expense" | "refund") | null;
                /** @description Comma-separated tags (AND) */
                tags?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of ledger entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation error (e.g. invalid date, limit) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_ledger_entry_api_v1_ledger_entries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LedgerEntryCreate"];
            };
        };
        responses: {
            /** @description Ledger entry created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Category or payment method not found or inactive */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_ledger_entry_by_id_api_v1_ledger_entries__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ledger entry with resolved names and currency */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Entry not found or soft-deleted */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid id format */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    put_ledger_entry_api_v1_ledger_entries__id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LedgerEntryCreate"];
            };
        };
        responses: {
            /** @description Ledger entry updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Entry not found, deleted, or category/payment method invalid */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_ledger_entry_api_v1_ledger_entries__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ledger entry soft-deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Entry not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid id format */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_monthly_expense_route_api_v1_analytics_monthly_expense_get: {
        parameters: {
            query: {
                /** @description Start date (YYYY-MM-DD) */
                from: string;
                /** @description End date (YYYY-MM-DD) */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Monthly expense and refund totals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation error (missing from/to, invalid format, from > to, range > 1 year) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_expense_by_category_route_api_v1_analytics_expense_by_category_get: {
        parameters: {
            query: {
                /** @description Month (YYYY-MM) */
                month: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Expense totals by category for the given month */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation error (missing or invalid month) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_expense_by_payment_method_route_api_v1_analytics_expense_by_payment_method_get: {
        parameters: {
            query: {
                /** @description Month (YYYY-MM) */
                month: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Expense totals by payment method for the given month */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation error (missing or invalid month) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_custom_expense_by_tags_route_api_v1_analytics_custom_by_tags_get: {
        parameters: {
            query: {
                /** @description Comma-separated tags (AND); at least one required */
                tags: string;
                /** @description Start date (YYYY-MM-DD) */
                from: string;
                /** @description End date (YYYY-MM-DD) */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Total expense for entries matching all given tags in date range */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation error (missing tags/dates, invalid format, from > to, range > max) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_dashboard_route_api_v1_analytics_dashboard_get: {
        parameters: {
            query: {
                /** @description Start date (YYYY-MM-DD) */
                from: string;
                /** @description End date (YYYY-MM-DD) */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard: totals, entry count, last entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation error (missing from/to, invalid format, from > to, range > max) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
